[tool.poetry]
name = "gform-automation"
version = "0.1.0"
description = ""
authors = ["kristianto wijaya <k.wijaya@verihubs.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
selenium = "4.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
